### PR TITLE
Allow newer versions of ruby-saml

### PR DESCRIPTION
**Pull request by alex**

### CODE REVIEW

**Comment by md5** [comment]
:+1:

**Comment by bpedro** [comment]
:+1: 

Thanks!

**Comment by md5** [comment]
Thanks @bpedro :metal:

**Comment by md5** [comment]
I'm seeing some test failures on `master` when running with `ruby-saml` version 1.1.0:

```console
$ bundle exec rspec
I, [2015-11-08T21:40:34.372008 #42278]  INFO -- omniauth: (saml) Request phase initiated.
D, [2015-11-08T21:40:34.373310 #42278] DEBUG -- : Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='http://localhost:3000/auth/saml/callback' Destination='https://idp.sso.target_url/signon/29490' ID='_5232d1d0-68d2-0133-3c73-245e60bc3bef' IssueInstant='2015-11-09T05:40:34Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/></samlp:AuthnRequest>
.I, [2015-11-08T21:40:34.378240 #42278]  INFO -- omniauth: (saml) Request phase initiated.
D, [2015-11-08T21:40:34.379213 #42278] DEBUG -- : Created AuthnRequest: <samlp:AuthnRequest AssertionConsumerServiceURL='http://localhost:3000/auth/saml/callback' Destination='https://idp.sso.target_url/signon/29490' ID='_5233b980-68d2-0133-3c74-245e60bc3bef' IssueInstant='2015-11-09T05:40:34Z' Version='2.0' xmlns:saml='urn:oasis:names:tc:SAML:2.0:assertion' xmlns:samlp='urn:oasis:names:tc:SAML:2.0:protocol'><samlp:NameIDPolicy AllowCreate='true' Format='urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress'/></samlp:AuthnRequest>
.I, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Digest mismatch
FI, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Digest mismatch
FI, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Digest mismatch
FI, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Digest mismatch
FI, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OmniAuth::Strategies::SAML::ValidationError, SAML response missing
.I, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OmniAuth::Strategies::SAML::ValidationError, SAML response missing 'name_id'
.I, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Fingerprint mismatch
.I, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Digest mismatch
.I, [2012-11-08T20:40:00.000000 #42278]  INFO -- omniauth: (saml) Callback phase initiated.
E, [2012-11-08T20:40:00.000000 #42278] ERROR -- omniauth: (saml) Authentication failure! invalid_ticket: OneLogin::RubySaml::ValidationError, Digest mismatch
...

Failures:

  1) OmniAuth::Strategies::SAML POST /auth/saml/callback when the response is valid should set the uid to the nameID in the SAML response
     Failure/Error: auth_hash['uid'].should == '_1f6fcf6be5e13b08b1e3610e7ff59f205fbd814f23'
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/omniauth/strategies/saml_spec.rb:80:in `block (4 levels) in <top (required)>'

  2) OmniAuth::Strategies::SAML POST /auth/saml/callback when the response is valid should set the raw info to all attributes
     Failure/Error: auth_hash['extra']['raw_info'].all.to_hash.should == {
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/omniauth/strategies/saml_spec.rb:84:in `block (4 levels) in <top (required)>'

  3) OmniAuth::Strategies::SAML POST /auth/saml/callback when fingerprint is empty and there's a fingerprint validator should set the uid to the nameID in the SAML response
     Failure/Error: auth_hash['uid'].should == '_1f6fcf6be5e13b08b1e3610e7ff59f205fbd814f23'
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/omniauth/strategies/saml_spec.rb:102:in `block (4 levels) in <top (required)>'

  4) OmniAuth::Strategies::SAML POST /auth/saml/callback when fingerprint is empty and there's a fingerprint validator should set the raw info to all attributes
     Failure/Error: auth_hash['extra']['raw_info'].all.to_hash.should == {
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # ./spec/omniauth/strategies/saml_spec.rb:106:in `block (4 levels) in <top (required)>'

Finished in 0.33139 seconds
13 examples, 4 failures

Failed examples:

rspec ./spec/omniauth/strategies/saml_spec.rb:79 # OmniAuth::Strategies::SAML POST /auth/saml/callback when the response is valid should set the uid to the nameID in the SAML response
rspec ./spec/omniauth/strategies/saml_spec.rb:83 # OmniAuth::Strategies::SAML POST /auth/saml/callback when the response is valid should set the raw info to all attributes
rspec ./spec/omniauth/strategies/saml_spec.rb:101 # OmniAuth::Strategies::SAML POST /auth/saml/callback when fingerprint is empty and there's a fingerprint validator should set the uid to the nameID in the SAML response
rspec ./spec/omniauth/strategies/saml_spec.rb:105 # OmniAuth::Strategies::SAML POST /auth/saml/callback when fingerprint is empty and there's a fingerprint validator should set the raw info to all attributes
Coverage report generated for RSpec to /Users/mike/Code/omniauth-saml/coverage. 67 / 71 LOC (94.37%) covered.
$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 7c68176..26904c2 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,15 +1,15 @@
 PATH
   remote: .
   specs:
-    omniauth-saml (1.3.1)
+    omniauth-saml (1.4.1)
       omniauth (~> 1.1)
-      ruby-saml (~> 1.0.0)
+      ruby-saml (~> 1.0)
 
 GEM
   remote: https://rubygems.org/
   specs:
     diff-lcs (1.2.4)
-    hashie (3.4.2)
+    hashie (3.4.3)
     macaddr (1.7.1)
       systemu (~> 2.6.2)
     mini_portile (0.6.2)
@@ -30,7 +30,7 @@ GEM
     rspec-expectations (2.14.4)
       diff-lcs (>= 1.1.3, < 2.0)
     rspec-mocks (2.14.4)
-    ruby-saml (1.0.0)
+    ruby-saml (1.1.0)
       nokogiri (>= 1.5.10)
       uuid (~> 2.3)
     simplecov (0.7.1)
@@ -49,3 +49,6 @@ DEPENDENCIES
   rack-test (~> 0.6)
   rspec (~> 2.8)
   simplecov (~> 0.6)
+
+BUNDLED WITH
+   1.10.6
```

I checked with `git bisect` and 416959b4721ad9acc56c209fa97c159bf3b3f873 appears to be the first failing commit, corresponding to this merge.

**Comment by md5** [comment]
Looks like the "Digest mismatch" errors are what's causing `auth_hash` to be `nil`.

**Comment by md5** [comment]
Looks like the digest checking failure was addressed in https://github.com/onelogin/ruby-saml/pull/282, released as v1.1.1. See https://github.com/onelogin/ruby-saml/pull/275 for more discussion.

I'm wondering whether the version specifier for `omniauth-saml` should be changed to this:

```ruby
gem.add_runtime_dependency 'ruby-saml', '~> 1.1', '>= 1.1.1'
```

**Pull request merged**
