### PR TITLE
Update to ruby-saml 0.9.1

### PR DESCRIPTION
**Pull request by thecarlhall**
This later version of ruby-saml supports more security options in the
saml assertion and metadata.

### CODE REVIEW

**Comment by OBCENEIKON** [comment]
This would be really nice to have.

**Comment by BrentWheeldon** [comment]
:+1:

**Comment by booleanbetrayal** [comment]
ruby-saml is actually updated to 0.9.2 (Apr 28, 2015) now, with a pending 1.0.0 release

**Comment by thecarlhall** [comment]
I had some trouble moving to 0.9.2 but don't recall specifically what it was.  You should be able to bump up to that version and run the tests to see it though.

**Comment by bpedro** [comment]
Closing because https://github.com/PracticallyGreen/omniauth-saml/pull/46 obsoletes this.

Thanks!

**Pull request closed without merging**
